FROM nginx:1.29.5-alpine3.23

RUN mkdir -p /var/cache/nginx

RUN chown -R nginx:nginx /var/cache/nginx
RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid

USER nginx

WORKDIR /usr/share/nginx/html